### ISSUE TITLE
Syntax Error Standalone Build

### ISSUE THREAD

**Issue by JeuneApprenti** [designsecurity/progpilot#11]
Hey there,

I've found the closed #10 issue that seems really close to mine, the only difference is that i'm running a Debian machine.

#### php's version :
` $ php -v` 
` PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )`

### What I Did
`$ wget https://github.com/designsecurity/progpilot/releases/download/v0.4.0/progpilot_v0.4.0.phar`
`$ php progpilot_v0.4.0.phar`

### What I Got

`PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in phar:///.../progpilot_v0.4.0.phar/vendor/symfony/console/Output/Output.php on line 40`

Did I do something obviously wrong ?

**Comment by JeuneApprenti** [comment]
Thanks you for this accurate and quick answer.

In my case and for now, i'm running the Stable `Debian v.9 "Stretch"` which do not have an apt php7.1's package, so i've opted for building my own phar archive.

Upon doing this, i've found some problems with the bash's build script you provided me :

#### 1. Composer's path

`Error : /home/eric/dev/phar-composer.phar doesn't exist` 
I've fixed it by editing the bash script and locate my composer.phar file at the _composertool_ variable declaration line (the third one).

#### 2. Command build not defined

Running the script again, it throw this error :
```
generating phar
  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "build" is not defined.
```
I don't know what to do from there, have you got any ideas ?

Paul

**Comment by eric-therond** [comment]
Have you downloaded the latest release of https://github.com/clue/phar-composer/releases ?
And specified the correct path of this tool in composertool variable of build.sh ?
If the problem persist paste your build.sh file here and how you have launched it.

Otherwise you could try this new archive :
https://github.com/designsecurity/progpilot/tree/master/builds

Eric

**Comment by JeuneApprenti** [comment]
Hello,

I've tried with https://github.com/clue/phar-composer and everything works properly now. 

Thank you a lot for your support, i'll now enjoy using Progpilot !

Paul
