### ISSUE TITLE
Installation instructions doesn't work with any stable php version

### ISSUE THREAD

**Issue by LANGERGabriel** [designsecurity/progpilot#15]
This is because the dev version of package ircmaxell/php-cfg uses typed property features from php7.4 (Though their composer.json has not been updated).

PHP version: <=7.3
Progpilot version: latest dev

Running vendor/bin/progpilot gives a parse error

**Comment by eric-therond** [comment]
thanks for the report @LANGERGabriel 
I have updated the version of ircmaxell/php-cfg to ^0.5 in composer.json
let me know if it doesn't fix the bug

Eric

**Comment by LANGERGabriel** [comment]
Works for me!
