### ISSUE TITLE
Unknown Expr Type NullableType

### ISSUE THREAD

**Issue by the6thBook** [designsecurity/progpilot#17]
I'm getting an error "Unknown Expr Type NullableType" when running progpilot against simplesamlphp

php progpilot_v0.7.0.phar /opt/simplesamlphp

Unknown Expr Type NullableType

$ php -v
PHP 7.2.24-0ubuntu0.18.04.3 (cli) (built: Feb 11 2020 15:55:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.3, Copyright (c) 1999-2018, by Zend Technologies

Thanks

**Comment by eric-therond** [comment]
Thanks @the6thBook for reported this bug
It has been fixed with the release v0.8.0 of Progpilot

Eric
