### ISSUE TITLE
Issue with setcookie

### ISSUE THREAD

**Issue by NicolasCARPi** [designsecurity/progpilot#18]
With the new released version, I can now try this software :)

There is an issue with `setcookie()` because it can also take an array of options as a third parameter, and the code is only taking into account the other way to specify options.

This code:
![2020-03-22-144947_384x134_scrot](https://user-images.githubusercontent.com/3043706/77251058-640b5500-6c4c-11ea-9842-1309ba855985.png)

Should not trigger this warning:

![2020-03-22-145018_668x174_scrot](https://user-images.githubusercontent.com/3043706/77251071-77b6bb80-6c4c-11ea-8ec6-22077ca7780c.png)

Cheers :)
~Nico

**Comment by eric-therond** [comment]
I have updated custom rules definition with two new parameters:
- the rule will not raise a vulnerability if the number of arguments in the function call  is less than `min_nb_args` parameter or greater than `max_nb_args` parameter.

You can [check here](https://github.com/designsecurity/progpilot/blob/master/package/src/uptodate_data/php/rules.json#L117) how the 4 custom rules related to setcookie() are now defined.

Should be ok now?
Eric

**Comment by NicolasCARPi** [comment]
Yes, I can confirm that it works now! :+1:
