### ISSUE TITLE
Failed to download designsecurity/progpilot

### ISSUE THREAD

**Issue by liming9515** [designsecurity/progpilot#2]
When i install this library with composer, throw this exception. 

**composer install**
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 9 installs, 0 updates, 0 removals
  - Installing phpdocumentor/graphviz (1.0.4): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v4.1.1): Downloading (100%)
  - Installing symfony/polyfill-mbstring (v1.8.0): Loading from cache
  - Installing symfony/console (v3.4.12): Downloading (100%)
  - Installing symfony/yaml (v3.3.17): Loading from cache
  - Installing nikic/php-parser (v4.0.2): Loading from cache
  - Installing ircmaxell/php-cfg (dev-master c8e78df): Cloning c8e78df992 from cache
  - Installing designsecurity/progpilot (dev-master 3aad8c6): Cloning 3aad8c6087
    **Failed to download designsecurity/progpilot from source: The process "git clone --no-checkout 'https://github.com/designsecurity/progpilot.git' '/Users/liming/workspace/php/demo/progpilot-test/vendor/designsecurity/progpilot' && cd '/Users/liming/workspace/php/demo/progpilot-test/vendor/designsecurity/progpilot' && git remote add composer 'https://github.com/designsecurity/progpilot.git' && git fetch composer" exceeded the timeout of 300 seconds.**
    Now trying to download from dist
  - Installing designsecurity/progpilot (dev-master 3aad8c6): Loading from cache
symfony/console suggests installing psr/log-implementation (For using the console logger)
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/lock ()
symfony/console suggests installing symfony/process ()
Writing lock file
Generating autoload files

**Comment by eric-therond** [comment]
Hello @liming9515,
It seems that it's not related to progpilot. 
Maybe you could clear the cache of composer and try again  :
> composer clearcache
> composer install

Or for testing try to clone the project directly from github : 
> git clone https://github.com/designsecurity/progpilot.git

Eric

**Comment by liming9515** [comment]
`composer clearcache` is working，thanks！
