### ISSUE TITLE
Unknown Node Encountered : Stmt_GroupUse

### ISSUE THREAD

**Issue by kaystrobach** [designsecurity/progpilot#20]
progpilot fails to run, when use statements are in use

**Comment by eric-therond** [comment]
Hello,
this is related to an issue (https://github.com/ircmaxell/php-cfg/issues/58) in the ircmaxell/php-cfg dependency. You can comment this issue to alert the maintainer?

On the progpilot side if you surround the analysis with `try`/`catch`,
the analysis will not fail when encountering an unknown node:

```
try {
   $analyzer->run($context);
} catch (Exception $e) {
   echo 'Exception : ',  $e->getMessage(), "\n";
}
```

**Comment by eric-therond** [comment]
Done in v1.0.0
