### ISSUE TITLE
dockerfile and wildcard ignore rules

### ISSUE THREAD

**Issue by ghost** [designsecurity/progpilot#26]
Hi guys,

Hope you are all well ! And happy new year to all your team and family :-)

I wanted to test progpilot on **prestashop** and could not find how to wildcard ignore rules for images/cache/xml filetypes.

How can I setup it in the config file ?

Here is my current config file: https://github.com/lucmichalski/progpilot/blob/docker/projects/example_config/configuration.yml#L17-L33

Also, I dockerized **progpilot** so if you want to include/customise it to a more generic use, please feel free to copy it:
ref: https://github.com/lucmichalski/progpilot/blob/docker/Dockerfile

Thanks for any inputs on insights on the config file :-)

Cheers,
Luc Michalski

**Comment by eric-therond** [comment]
Hi @lucmichalski 
happy new year!

You can't use wildcard when excluding files or folders, progpilot read all files in scope and will continue the analysis (try to parse php code) for the ones that begin by `<?` or `<?php`. If your project is well organized and it's hopefully the case for prestashop, you can quickly identify folders that contain assets and exclude them.

To define the scope of the analysis you can also select only some folders with this kind of config:
```
setIncludes:
        include_folders: 
            - "./src/"
```

Eric
