### ISSUE TITLE
THE TOOL IS BROKEN 😭 !!

### ISSUE THREAD

**Issue by co-valtira** [designsecurity/progpilot#29]
1. when I clone the code from the repo and run ./build.sh i get this error:
[Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "build" is not defined.  because this block of code doesn't work in bash script : php -d phar.readonly=off "$(command -v phar-composer.phar)" build .

2. when I simply run progpilot /path/to/code.php after downloading the lates release this error is thrown on my mac: 
Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in phar:///Users/$USER/progpilot_v0.8.0.phar/vendor/nikic/php-parser/lib/PhpParser/Parser/Php5.php on line 2623

3. I spun up an AWS ec2 instance with 60gig ram and after working through dependency issues and all kinds of errors  this is the final error it throws:
PHP Notice:  Undefined offset: 0 in phar:///usr/local/bin/progpilot/vendor/progpilot/package/src/progpilot/Analysis/ResolveDefs.php on line 559
PHP Notice:  Undefined offset: 0 in phar:///usr/local/bin/progpilot/vendor/progpilot/package/src/progpilot/Analysis/ResolveDefs.php on line 559
PHP Notice:  Undefined offset: 0 in phar:///usr/local/bin/progpilot/vendor/progpilot/package/src/progpilot/Analysis/ResolveDefs.php on line 559
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in phar:///usr/local/bin/progpilot/vendor/progpilot/package/src/progpilot/Objects/MyFunction.php on line 82

**Comment by eric-therond** [comment]
Hi @co-valtira 

1. Can you check there are no previous errors while running `./build.sh` and if yes copy paste them here.
2. Memory problems with progpilot is a known issue, I plan to do something about it but nothing is excepted soon, more at the end of the year. For now, you can try to deal with this limitation by reading [this part of the documentation](https://github.com/designsecurity/progpilot/blob/master/docs/FAQ.md#when-i-use-progpilot-i-often-run-out-of-memory).
3. Same thing + another problem on `ResolveDefs.php` added to the backlog.

**Comment by eric-therond** [comment]
if you have time to try with the latest progpilot version (v1.0.0)

Eric

**Comment by eric-therond** [comment]
progpilot version (v1.0.2) solves this.
