### ISSUE TITLE
Uncaught Error: Call to a member functio toString() on null

### ISSUE THREAD

**Issue by the6thBook** [designsecurity/progpilot#31]
I'm getting the following error using progpilot 0.8.0 with php 7.4.20:

PHP Fatal error:  Uncaught Error: Call to a member function toString() on null in phar:///home/centos/progpilot/progpilot/vendor/ircmaxell/php-cfg/lib/PHPCfg/AstVisitor/MagicStringResolver.php:32
Stack trace:
#0 phar:///home/centos/progpilot/progpilot/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(123): PHPCfg\AstVisitor\MagicStringResolver->enterNode(Object(PhpParser\Node\Stmt\Class_))
#1 phar:///home/centos/progpilot/progpilot/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(146): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Expr\New_))
#2 phar:///home/centos/progpilot/progpilot/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->traverseNode(Object(PhpParser\Node\Stmt\Return_))
#3 phar:///home/centos/progpilot/progpilot/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(114): PhpParser\NodeTraverser->traverseArray(Array)
#4 phar:///home/centos/progpilot/progpilot/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(223): PhpParser\NodeTraverser->trave in phar:///home/centos/progpilot/progpilot/vendor/ircmaxell/php-cfg/lib/PHPCfg/AstVisitor/MagicStringResolver.php on line 32

Thanks

**Comment by CDelugeau** [comment]
Same problem. php-cfg has a tag 0.6.0 since april. Can you update your composer.json to this version ?

**Comment by eric-therond** [comment]
if you have time to try with the latest progpilot version (v1.0.0)

Eric

**Comment by eric-therond** [comment]
progpilot version (v1.0.2) solves this.
