### ISSUE TITLE
After try to install with composer get error "Your requirements could not be resolved to an installable set of packages."

### ISSUE THREAD

**Issue by r00t3r5** [designsecurity/progpilot#33]
After i try to install with composer i get error this is full error from terminal. 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires designsecurity/progpilot ^0.8.0 -> satisfiable by designsecurity/progpilot[v0.8.0].
    - designsecurity/progpilot v0.8.0 requires ircmaxell/php-cfg 1.0.x-dev -> found ircmaxell/php-cfg[v1.0.x-dev] but it does not match your minimum-stability.

Installation failed, deleting ./composer.json.

**Comment by matmalone** [comment]
Your composer init needs to specify a minimum-stability of dev in order to get php-cfg to install. Include this in your composer.json:
```
    "minimum-stability": "dev",
```
From there I was able to get it to update the dependencies without an issue.

**Comment by eric-therond** [comment]
if you have time to try with the latest progpilot version (v1.0.0)

Eric

**Comment by eric-therond** [comment]
progpilot version (v1.0.2) should solve this.
