### ISSUE TITLE
Unknown type node: UnionType

### ISSUE THREAD

**Issue by chogberg** [designsecurity/progpilot#34]
Hi,

When I try to analyze some code I get `Unknown type node: UnionType` as a result. I can´t really figure out what this means. There must be something wrong with Main.php but can't figure out what :
`<?php
    require('../../sys/classes/Main.php');`

**Comment by eric-therond** [comment]
if you have time to try with the latest progpilot version (v1.0.0)

Eric

**Comment by eric-therond** [comment]
progpilot version (v1.0.2) should solve this.
