### ISSUE TITLE
How to define the most strict configuration possible for  Progpilot ?

### ISSUE THREAD

**Issue by vic131** [designsecurity/progpilot#39]
I’m collaborating in a opensource project :

https://bitbucket.org/AliasAPI/damnp/src/master/etc/progpilot/run_progpilot.sh

And i am finding trouble configuring Progpilot  in the most sensitive way possible, so it would detected every generally undesired line of code. If anyone has any tips, it would be very welcome.

**Comment by eric-therond** [comment]
Hello, sorry for the delay
by default progpilot has the strictest configuration possible

you can still play a bit with maximum analysis duration/max memory/max file size options, see the last 3 lines here: https://github.com/designsecurity/progpilot/blob/master/projects/example_config/configuration.yml#L35
but it is something a bit experimental, it can have a high impact on performances.
