### ISSUE TITLE
PHP Fatal error:  Cannot use 'Mixed' as class name as it is reserved in phar:///usr/local/bin/progpilot/vendor/ircmaxell/php-cfg/lib/PHPCfg/Op/Type/Mixed.php on line 16

### ISSUE THREAD

**Issue by adabiraihan** [designsecurity/progpilot#44]
Hello,

I'm installing with option 1 (phar), and I'm encountering this error

PHP Fatal error:  Cannot use 'Mixed' as class name as it is reserved in phar:///usr/local/bin/progpilot/vendor/ircmaxell/php-cfg/lib/PHPCfg/Op/Type/Mixed.php on line 16

any idea? thanks

**Comment by eric-therond** [comment]
Hello
Did you try the latest progpilot version?
https://github.com/designsecurity/progpilot/releases/tag/v1.0.0

Eric

**Comment by adabiraihan** [comment]
yes sirr,

![image](https://user-images.githubusercontent.com/43380235/211261186-ea7d7827-b4b6-4e74-bd03-0896c501fa0c.png)

**Comment by adabiraihan** [comment]
ok Eric, by the way thanks for the fast response  :)

Thank You!

**Comment by eric-therond** [comment]
I let you test with this new one:
https://github.com/designsecurity/progpilot/releases/tag/v1.0.1

Eric

**Comment by adabiraihan** [comment]
no luck sorry, it raise a new error

PHP Fatal error:  Declaration of progpilot\Console\Application::run(?Symfony\Component\Console\Input\InputInterface $input = null, ?Symfony\Component\Console\Output\OutputInterface $output = null) must be compatible with Symfony\Component\Console\Application::run(?Symfony\Component\Console\Input\InputInterface $input = null, ?Symfony\Component\Console\Output\OutputInterface $output = null): int in phar:///usr/local/bin/progpilot/vendor/progpilot/package/src/progpilot/Console/Application.php on line 27

**Comment by eric-therond** [comment]
It's a shame... I have no excuses, this project lacks of tests about the console/phar application
I hope this one is ok now: https://github.com/designsecurity/progpilot/releases/tag/v1.0.2

Eric

**Comment by adabiraihan** [comment]
works like a charm, thanks Eric !
