### ISSUE TITLE
Some enhancements

### ISSUE THREAD

**Issue by eapunk** [designsecurity/progpilot#6]
Hello @eric-therond 
I have just published project [svscan](https://github.com/hardsoft321/svscan) based on progpilt.
Maybe you are interesting what features will be useful to have in progpilot.
I overrode some code to achieve the following:
 - multiple rules, i.e. your uptodate data and my custom rules
 - counting the number of files analyzed
 - printing result at the same moment when it founded

You can close this issue at any time.

Thank you for your project.

**Comment by eric-therond** [comment]
Hello @eapunk 
thank you very much for your efforts
I have integrated most of your work in the [0.3.3 version](https://github.com/designsecurity/progpilot/tree/master/builds) of progpilot :

- an array of files could be passed for specifying an analysis, for example :
```php
$obj_context->inputs->setSources(["sources1.json", "sources2.json"]);
```
- the number of analyzed files could be retrieved with this method : 
```php
$obj_context->outputs->getCountAnalyzedFiles();
```

- and a callback function could be executed when a bug is found : 
```php
$obj_context->outputs->setOnAddResult($func);
```
I hope this is what you expected

Eric
