### ISSUE TITLE
phar-composer.phar should be located in a directory listed in the $PATH environment variable

### ISSUE THREAD

**Issue by taiwoswot** [designsecurity/progpilot#60]
For window users, which path exactly or in which specific folder should phar-composer.phar be placed?

**Comment by eric-therond** [comment]
- download the latest release of phar composer tool: https://github.com/clue/phar-composer/releases
- make it executable and add it in a folder in your PATH

for more information about path env in Windows : https://www.computerhope.com/issues/ch000549.htm

I am closing the issue as it's not related to progpilot.
