### ISSUE TITLE
progpilot gives erroneous version info

### ISSUE THREAD

**Issue by the6thBook** [designsecurity/progpilot#8]
$ php progpilot_v0.2.0.phar -V /opt/ECMS2/www/index.php
progpilot 0.1.0
$ php progpilot_v0.3.0.phar -V /opt/ECMS2/www/index.php
progpilot 0.1.0

**Comment by eric-therond** [comment]
thanks for the feedback,
the last dev version has the good version number : 
https://github.com/designsecurity/progpilot/tree/master/builds

And I will try to not forget for the next releases
