### ISSUE TITLE
link to /home/eric

### ISSUE THREAD

**Issue by Mielai1l** [designsecurity/progpilot#9]
https://github.com/designsecurity/progpilot/blob/c2248a35d21d6dcdb082880f2f967f2a3db7a054/build.sh#L5
This refers to composertool=/home/eric/dev/phar-composer.phar
which will not work for another user

**Comment by eric-therond** [comment]
Hello
now the script checks if the file exists and proposes a solution otherwise

Hope it's ok for you ?
Eric
